name: Build and attach release asset

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tagged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Create zip
        run: zip -r bluetooth.koplugin.zip ./bluetooth.koplugin/

      - name: Upload asset to the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: bluetooth.koplugin.zip